### ISSUE TITLE
Unable to launch terraform plan due to an input variable not being assigned 

### ISSUE THREAD

**Issue by black-fyr3** [hashicorp/terraform-plugin-sdk#1009]
I'm currently trying to work with terraform module testing (which came out with the 0.15 version).

My goal is to test the code featured within a sub-folder found in the tests folder through the terraform test command.

In this specific case, after initialising terraform and running the test command I've been receiving this error:
```
Error: Unassigned variable

The input variable "api_url" has not been assigned a value. This is a bug in Terraform; please report it in a GitHub issue.
```
My folders / subfolders are as follows:

My main.tf:

```
variable "api_url" {
  description = "A URL that you would like to test"
  default = "https://google.com"
  type = string
}

output "api_url" {
  value = var.api_url
}
```
My terraform.tfvars

```
api_url = "https://google.com"
```

My tests/default (containing the test_assertions)

```
terraform {
  required_providers {
      test = {
          source = "terraform.io/builtin/test"
      }

      http = {
          source = "hashicorp/http"
      }
  }
}

variable "api_url" {
  type = string
  default = "http://msn.com"
}

module "main" {
    source = "../.."
    api_url = var.api_url
    
}

locals {
  api_url_parts = regex(
    "^(?:(?P<scheme>[^:/?#]+):)?(?://(?P<authority>[^/?#]*))?",
    module.main.api_url,
  )
}

resource "test_assertions" "api_url" {
  
  component = "api_url"

  equal "scheme" {
    description = "default scheme is https"
    got         = local.api_url_parts.scheme
    want        = "https"
  }

  check "port_number" {
    description = "default port number is 8080"
    condition   = can(regex(":8080$", local.api_url_parts.authority))
  }
}

data "http" "api_response" {
  depends_on = [
    test_assertions.api_url,
  ]

  url = module.main.api_url
}

resource "test_assertions" "api_response" {
  component = "api_response"

  check "valid_json" {
    description = "base URL responds with valid JSON"
    condition   = can(jsondecode(data.http.api_response.body))
  }
}
```
If it helps, this code was gathered from the following github repository (https://github.com/ned1313/terraform-tuesdays/tree/main/2021-05-04-ModuleTesting)

I'm running this on an AWS Linux VM (amd64) running on Terraform v1.2.5

Any help would be greatly appreciated, thanks.

**Comment by bflad** [comment]
Hi @black-fyr3 👋 Thank you for raising this issue and sorry you ran into trouble with Terraform here.

This repository contains bug reports and feature requests relating to the Terraform Plugin SDK, which is a coding framework for developing and testing Terraform Providers. There are two exceptions to Terraform Providers to which this applies to, which are those that have a source of `terraform.io/builtin/`, which are built within Terraform core/CLI.

If you have a bug report or feature request with Terraform core functionality, please [open an issue in the tracker for that codebase](https://github.com/hashicorp/terraform/issues). If you have a question about Terraform core functionality or module testing in general, please [open a post in HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-core/27). Since there does not appear to be anything actionable for this codebase in this issue report, I'm going to close this issue.

---

Aside: [Terraform 1.2 introduced pre and post conditions](https://www.hashicorp.com/blog/terraform-1-2-improves-exception-handling-and-updates-to-the-cli-driven-workflow), which may be easier to work with or more desirable than the built-in `test` provider in your situation. The people who maintain that Terraform core functionality would be much more authoritative on any recommendations in this space though.
