### ISSUE TITLE
execute resources arguments according to condition

### ISSUE THREAD

**Issue by rampanwar1** [hashicorp/terraform-plugin-sdk#1183]
Hi terraform community,
     I am going to deploy azure PostgreSQL database using  Terraform.Can i add condition for resource argument. If my value is "true" resource argument should be  execute for this resource if value is false argument should not execute. is there any way in Terraform ?.
     
  resource "azurerm_mysql_flexible_server" "mysql" {
     name                   = local.workspace["name"]
     private_dns_zone_id    = existing_resources   = local.workspace["create_new_resources"] == true ? 1 : 0

**Comment by bendbennett** [comment]
Hi @rampanwar1 👋 

The docs for [mysql_flexible_server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server) indicate the following for `private_dns_zone_id`:

> - (Optional) The ID of the private DNS zone to create the MySQL Flexible Server. Changing this forces a new MySQL Flexible Server to be created.
 
I'm therefore assuming that you want to conditionally include `private_dns_zone_id` in the configuration?

If so, then you should be able to use the following pattern:

```terraform
resource "azurerm_mysql_flexible_server" "mysql" {
  name = local.workspace["name"]
  private_dns_zone_id = local.workspace["create_new_resources"] == false ? null : "<azurerm_private_dns_zone.example.id>"
```

You'll need to substitute `<azurerm_private_dns_zone.example.id>` with the appropriate ID as illustrated in the [example usage](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#example-usage) in the docs.

We try to keep questions out of the GitHub issues because it's harder for people in future to find the answers, so I'd ask that in future questions be directed to one of the forums on [Discuss](https://discuss.hashicorp.com/).

If you have any further questions about the above, please use Discuss, since it's hard for us to track ongoing Q&A within the GitHub issues UI.

Thanks!
