### ISSUE TITLE
Inconsistent Optional w/ Default behavior

### ISSUE THREAD

**Issue by tylerFowler** [hashicorp/terraform-plugin-sdk#1185]
### SDK version
v2.24.1

```
...
```

### Relevant provider source code

```go
schema.Schema{
  Type: schema.TypeString,
  Default:      "Some default",
  Optional:     true,
  Computed:     true,
}
```

### Debug Output
```
resource my_resource: some_attribute: Default must be nil if computed
```

### Expected Behavior
Per the [SDK documentation](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Schema):

```go
        // Optional indicates whether the practitioner can choose to not enter
	// a value in the configuration for this attribute. Optional cannot be used
	// with Required.
	//
	// If also using Default or DefaultFunc, Computed should also be enabled,
	// otherwise Terraform can output warning logs or "inconsistent result
	// after apply" errors.
	Optional [bool](https://pkg.go.dev/builtin#bool)
```

### Actual Behavior
This recommendation of supplying "Computed" when both "optional" and with a "default" seems to produce an error suggesting that "Computed" attributes must never have a default.

**Comment by bflad** [comment]
Hi @tylerFowler 👋 Thank you for raising this and sorry you ran into this confusing contradiction in the Go documentation.

This additional documentation was added as part of #912 along with a bunch of other schema documentation changes. I'm guessing I was _optimistically_ trying to document what Terraform normally expects from providers in this case, but didn't explicitly verify that it was actually possible in this SDK. This SDK sets a special flag when communicating with Terraform that enables some demotes some Terraform data consistency errors to warning logs. Newer SDKs, such as terraform-plugin-framework, intentionally do not set this special flag so provider developers are always aware of schema definition or data handling logic issues.

Rather than potentially removing the schema implementation validation logic for this:

```go
if v.Computed && v.Default != nil {
	return fmt.Errorf("%s: Default must be nil if computed", k)
}
```

And have other potential unexpected behaviors introduced for provider developers if they _do_ try to set `Computed: true` and `Default: ...`, the safer option here will unfortunately be removing the invalid documentation from the `Optional` field to match the current implementation.

**Comment by tylerFowler** [comment]
This is totally fine, just wanted to ensure that the version of the logic is in fact the correct one. My changeset that led me to this was one in response to seeing messages in Terraform logs like "provider xxxx unexpectedly produced new value for attribute Y ..."
