### ISSUE TITLE
Crash after moving resource location in state, init and apply

### ISSUE THREAD

**Issue by arcones** [hashicorp/terraform-plugin-sdk#119]
### Terraform Version
```
➜  terraform -v
Terraform v0.11.8
+ provider.archive v1.1.0
+ provider.aws v1.38.0
+ provider.template v1.0.0
```

### Crash Output
[crash.log](https://github.com/hashicorp/terraform/files/2437566/crash.log)

### Steps to Reproduce
1) `terraform state mv module.app.aws_iam_role.lambda module.app.module.lambda.aws_lambda_function.lambda`
2) `terraform init`
3) `terraform apply`

**Comment by radeksimko** [comment]
Hi @arcones 
thank you for the bug report.

Unfortunately because the report doesn't contain configuration that I could take and try to reproduce the bug I will have to make assumptions.

Given the first line of traceback being

```
panic: Error reading level state: strconv.ParseInt: parsing "74D93920-ED26-11E3-AC10-0800200C9A66": invalid syntax
```

The root cause seems to be the magic string `74D93920-ED26-11E3-AC10-0800200C9A66`, which is the way [unknown values were internally represented](https://godoc.org/github.com/hashicorp/terraform/vendor/github.com/hashicorp/hil#pkg-constants) in 0.11 and earlier versions in HIL (HashiCorp Interpolation Language). HIL is practically no longer in use by Terraform 0.12 itself and types are represented more "sanely" (without needing such magic strings) via [cty](https://github.com/zclconf/go-cty).

The SDK still uses HIL today as it maintains backward compatibility, so it effectively translates enriched/safer types into the old type system.

With all that in mind it is less likely that you would run into this exact bug in 0.12 as core itself has much stricter validation with the new type system.

That said there are no guarantees and I would invite you to open a new issue if you manage to reproduce this bug in any way with Terraform 0.12 and latest version of the AWS provider.
