### ISSUE TITLE
Allow provider discovery as part of testing framework

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-plugin-sdk#13]
Acceptance tests of some providers depend on other providers, commonly on `template`, `tls`, or K8S depends on GCP (as it uses GCP to create some storage to test K8S storage APIs).

This has previously been achieved by importing providers as Go packages into the providers which depend on them. Each such provider brings in its own dependency tree which has impact on the dependency tree of the provider being tested. Adding a new provider is also a lot more involved process than it should/can be - one has to add the provider as a dependency and raise a big PR, before actually using it.

It would therefore be great if the testing framework just had the capability of discovering providers, like the CLI does today. That way developers don't need to worry about what providers do they depend on as these will just be downloaded automatically in the form of binaries, as part of each test run.

We might not want to download the same binary (provider of a particular version) more than once during 1 test run. Providers may have hundreds of MB. It would therefore be great if providers can be cached during each test run and downloaded only once.

**Comment by kmoe** [comment]
To summarise the concerns above and some discussion in an internal RFC: 

We need provider acceptance tests to be able to use resources from other providers, because this is often the only way to test real-world usage of certain resources (such as the example given by @tombuildsstuff).

The legacy test framework allows providers to import other providers for use in acceptance tests. We would like to move away from this, for the reasons described in @radeksimko's initial issue text, as well as importing providers as Go modules being against current [documented best practices](https://www.terraform.io/docs/extend/best-practices/depending-on-providers.html). 

Enabling Terraform CLI's plugin discovery mechanism as part of the new binary test driver would lead to the problems described by @apparentlymart: provider acceptance tests are now subject to new sources of non-determinism, namely changes in other providers falling within the allowed version range, custom builds of providers that happen to be installed to the provider path on the machine on which the tests are run, and network connectivity issues during the provider discovery step.

The new test driver will aim to avoid adding new sources of uncertainty in tests, while still moving away from the outdated practice of providers importing other providers. The current draft solution involves including binaries (which can be compressed) of other providers in a special `terraform.d` directory in the provider source code, so no changes can be made outside version control.
