### ISSUE TITLE
Allow provider to get value from config or prior state explicitly

### ISSUE THREAD

**Issue by rcohenma** [hashicorp/terraform-plugin-sdk#133]
I work on the OCI terraform provider
We are encountering a problem in our update functions on lists of nested objects.
Terraform's GetOk/GetOkExists do not allow us to distinguish whether a property value comes from the customer's config or the statefile.
This is a problem when we try to update a list of nested objects that have optional parameters.
We had solved this problem before by converting the TypeList into a TypeSet but now we are adding a new feature where the order of the list matters to the backend service so we had to disable the update on that List because we were not passing to the service what the user had in its config.

Example of the problem:
Lets say i have a TypeList  paramter "listPar" in which its elements have optional properties "optA" and "optB" of typeString
Lets say the user initially createad a resource with one element on the list

```
resource "..." "..." {
   listPar {
      optB = "1"
   }
}
```

now the user wants to update to add another element at the beginning of the list:
```
resource "..." "..." {
   listPar {
      optA = "0"
   }
   listPar {
      optB = "1"
   }
}
```
In this case because of the existing statefile and because getOk/getOkExists get the value of a property from the statefile if it is not in the config then we would be sending to the service something that the user did not specify in the config
```
UpdateRequest {
    listPar = [
        {optA=0, optB=1},
        {optB=1},
    ]
}
```

The statefile contains
```
 "... .listPar.0.optB" = 1
```
So on the Update when we do GetOk on the properties of the first element we will be getting a value for optB even if the user did not specify it in the config.

Thanks

**Comment by adampurser-zendesk** [comment]
Hey @rcohenma, 

> We had solved this problem before by converting the TypeList into a TypeSet

How did you solve this by using TypeSet instead? I'm still running into the same issues after converting.

**Comment by pezeli2002** [comment]
Could we please have an update on this?

**Comment by bflad** [comment]
Hi folks 👋 

As of version 2.8.0 of the Terraform Plugin SDK, there is experimental functionality to read the raw configuration, plan, and state data that was stored the beginning of the ApplyResourceChange, PlanResourceChange, ReadDataSource, and ReadResource RPCs:

* https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceData.GetRawConfig
* https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceData.GetRawPlan
* https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceData.GetRawState
* https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceDiff.GetRawConfig
* https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceDiff.GetRawPlan
* https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceDiff.GetRawState

More details and functionality surrounding the `cty.Value` returned by these methods can be found in the [`github.com/zclconf/go-cty/cty` package](https://pkg.go.dev/github.com/zclconf/go-cty/cty).

Familiarity with [protocol version 5](https://github.com/hashicorp/terraform-plugin-go/blob/main/tfprotov5/internal/tfplugin5/tfplugin5.proto) and which data is available with each RPC is encouraged before attempting to use this functionality (e.g. ReadResource only has state information). Raw plan data is not updated by any changes caused by a resource's `CustomizeDiff` function.

The SDK may not make it trivial to work with this new data yet. If you have specific feature requests surrounding this, please reach out by creating a new issue. If you have questions around this advanced functionality, please reach out by creating a new topic in [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43). Thanks.

---

Aside: The [Terraform Plugin Framework](https://www.terraform.io/plugin/framework), under active development, also provides direct access to the configuration, plan (which is updated during plan modifications), and state data. There is a [HashiCorp Learn tutorial](https://learn.hashicorp.com/tutorials/terraform/plugin-framework-create) and [template repository](https://github.com/hashicorp/terraform-provider-scaffolding-framework) available if you are interested in trying out that refreshed provider development model. See also: [Which SDK Should I Use?](https://www.terraform.io/plugin/which-sdk)
