### ISSUE TITLE
Documentation on Writing Custom Providers doesn't explain MyClient

### ISSUE THREAD

**Issue by clebio** [hashicorp/terraform-plugin-sdk#135]
I was working through the docs for Writing Custom Providers, implementing the `terraform-provider-example` that it shows, but things break down at [Implementing Read](https://learn.hashicorp.com/terraform/development/writing-custom-terraform-providers#implementing-read) since the example refers to a `MyClient` which is never defined. I understand that this is meant as a stand-in for an actual client API, but up until that point, the docs are an actual, working example.

```go
func resourceServerRead(d *schema.ResourceData, m interface{}) error {
  client := m.(*MyClient)
// ...
}
```

I don't yet have an example (or dummy) implementation of `MyClient` in mind, so no PR, but this seems like a mistake or omission in that piece of the documentation.

**Comment by bflad** [comment]
Thank you for submitting this so long ago, @clebio, it is great feedback. 😅 

Since this was raised the Learn guides for developing providers have been reworked. The new guide can be found here: https://learn.hashicorp.com/tutorials/terraform/provider-setup?in=terraform/providers

I don't believe it suffers from the same issue anymore as its currently using the "HashiCups" API and client, so I'm going to close this. Thanks again for the feedback though and apologies that it sat lingering in this issue tracker. I believe the team that manages the Learn content may be looking to make all the tutorial source code public on GitHub (and that would include its own issue tracking), but I'm not aware of further details of that project and if/when it might occur.
