### ISSUE TITLE
Force New When

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/terraform-plugin-sdk#14]
https://github.com/terraform-providers/terraform-provider-azurerm/issues/3713

Today ForceNew is all or nothing - it’d be great to conditionally model the migration paths to be able to say “migration between value A and B is possible, but to go from value B and A requires a new resource”

**Comment by bflad** [comment]
As mentioned above, using `CustomizeDiff` is the methodology to achieve this in this SDK. I don't think we would want to invest in yet-another-Schema-field to make this easier, since there are already too many fields to confuse provider developers. 👍 

Over in [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework), you can the choose between the built-in [`RequiresReplace`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/tfsdk#RequiresReplace) or [`RequiresReplaceIf`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-framework/tfsdk#RequiresReplaceIf) plan modifiers, rather than there being schema fields.
