### ISSUE TITLE
HasChange returns false for SetNewComputed attributes

### ISSUE THREAD

**Issue by ocharles** [hashicorp/terraform-plugin-sdk#165]
### Terraform Version

```
Terraform v0.12.0
```

### Bug

I have a custom provider that is using `SetNewComputed` in `CustomizeDiff`, as one attribute is always computed. When I `Update` the resource, if this attribute has a computed value, I need to go off and perform the update. However, in 0.12 we're finding that `HasChange` always returns `false`, even if `SetNewComputed` is called.

https://github.com/circuithub/terraform-provider-nix/blob/f6e2ed11e9e6401d9474e5bf1e3d83ef44856ef2/resource_nixos.go#L297 is where we call `SetNewComputed`, and https://github.com/circuithub/terraform-provider-nix/blob/f6e2ed11e9e6401d9474e5bf1e3d83ef44856ef2/resource_nixos.go#L223 is where we use `HasChange`. I've found that if `SetNewComputed` is changed to `SetNew` then `HasChange` returns `true` and all is well. However, if `SetNewComputed` is used, `HasChange` is always `false`, even when `terraform plan` shows:

```
~ nixos_system      = "/nix/store/f79yfwa32x3rdz17xybrj8dcjl9y1qn4-nixos-system-vault.circuithub.com-19.03pre-git" -> (known after apply)
```

It's unclear to me whether or not this is a bug, or an intended semantic change in how `HasChange` works.

**Comment by bflad** [comment]
I believe the originally reported issue behavior is (unfortunately) expected in this case. As mentioned above, some of the semantics around handling "unknown" values are ambiguous and certain providers may be reliant on the current behavior of `SetNewComputed` not triggering `HasChange` since the "unknown" value could technically be the same value. If possible it is best to use `SetNew`.

Changing this behavior would likely need to be done in a new major version of this project for compatibility reasons, in which there are no further plans to make another one due to our focus on [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework). The good news there is that the newer framework enables providers to directly inspect whether values are null, unknown, or known between the configuration, plan, and state, so there should be enough data to handle any situation like this without an abstraction getting in the way. 👍
