### ISSUE TITLE
ignore_changes not ignoring a change which uses a dynamic value

### ISSUE THREAD

**Issue by anuraaga** [hashicorp/terraform-plugin-sdk#167]
### Terraform Version

```
Terraform v0.12.5
```

### Terraform Configuration Files

```hcl
resource kubernetes_deployment deployment {
  lifecycle {
    ignore_changes = [spec[0].template[0].metadata[0].labels["revision"]]
  }
  spec {
    template {
      metadata {
        labels = {
          name = var.name
          revision = "terraform-${timestamp()}"  // Key line
...
}
```

### Expected Behavior

Change is ignored because the value is changed, not added or removed.

### Actual Behavior

Change is not ignored with output like
```
                  ~ labels      = {
                      - "name"     = "server-alpha"
                      - "revision" = "8d6c139eeded8df121fa13aca5404e6bb60a2dca"
                    } -> (known after apply)
```

If the revision is set to just "terraform" in the config, it works - as you can see, the value changes from that git hash to the word "terraform" but plan shows no updates. I don't think it should matter whether the value is dynamic or not for whether it is ignored or not.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by JnMik** [comment]
I have a similar issue using Stakater-Reloader.
It creates environment variables on the resource to know if it needs to reload it or not, like this : 
![image](https://user-images.githubusercontent.com/4965516/99409252-2afcb080-28bf-11eb-9292-30585863dffa.png)

And I'm not able to ignore_changes on these specific environment variables, I tried that : 
![image](https://user-images.githubusercontent.com/4965516/99409324-3ea81700-28bf-11eb-8055-ef90ec2e212e.png)

But it's not working, however if I ignore all the ENV then it's fine, but I might have other environment variables that I want terraform to detect the changes.

**Comment by paddycarver** [comment]
I think this issue got transferred to this repository on accident, because this is all functionality of Terraform core, and isn't related to the SDK at all, which is what this repo is for. I'm going to close this issue out, because it's been quite some time since it was first reported, and the functionality that is being discussed has been completely rewritten since this issue was opened. If you feel you're having this issue or a related issue still, I'd encourage you to open an issue in hashicorp/terraform, being sure to fill out the issue template fully so the team over there can get to the bottom of it.
