### ISSUE TITLE
Computed True not working as expected for nested schemas

### ISSUE THREAD

**Issue by code-lucidal58** [hashicorp/terraform-plugin-sdk#208]
While writing a provider, I have a complex Property A which has sub-properties X,Y, and Z, of which Y and Z are computed, but not X, in the schema. I marked A also computed. hence it looks as below:
```go
"a": {
   Type:        schema.TypeList,
   Optional:    true,
   Elem: &schema.Resource{
      Schema: map[string]*schema.Schema{
         "x": {
            Type:        schema.TypeString,
            Optional:    true,
         },
         "y": {
            Type:        schema.TypeString,
            Computed:    true,
            Optional:    true,
         },
         "z": {
            Type:        schema.TypeString,
            Computed:    true,
            Optional:    true,
         },
      },
   },
   Computed: true,
}
```
Now, I create a resource, assign some value to A's X
```hcl2
resource "provider_dummy" "dummy1" {
a {
    x = "hello"
 }
dummy_prop1 = "dummyvalue1"
dummy_prop2 = "dummyvalue2"
}
```
I do a ```terraform apply```. Next, I make a change to this resource. I comment out the entire property A. Hence, the updated tf is:
```hcl2
resource "provider_dummy" "dummy1" {
dummy_prop1 = "dummyvalue1"
dummy_prop2 = "dummyvalue2"
}
```

Now, do a ```terraform plan```. Terraform shows "no changes".

### Expected Output 
it should show that the resource "dummy" is updated.

**Comment by code-lucidal58** [comment]
If the computed true is removed from the parent property, then the above issue is resolved, but a new one comes to scene. 
Computed values are received as a part of ```terraform apply``` and the statefile also stores them. When ```terraform plan``` is done, the diff shows that "those properties (i.e. the subproperties that are marked as computed) should be null, but the have values now. Hence make them null again"

**Comment by paultyng** [comment]
This is related to core's concepts of blocks and attributes, going to merge it with #321.

The problem is that these concepts don't translate properly to this SDK since this SDK is coupled to some legacy Terraform concepts. The issue being here that a removed config block is not an implicit zeroing of that block, but just a deferral to computed state. When a block is computed, and you remove that block, Terraform does not think you are removing/destroying anything, just that you are deferring to the upstream to handle it and is a limitation unfortunately. You can tell this to use attribute mode instead of block mode as a workaround, but its more of a legacy concept that is not ideal. To do that, set the `ConfigMode` to `schema.SchemaConfigModeAttr`.

Here is an example: https://github.com/terraform-providers/terraform-provider-google/blob/aab740298c14748faf5e4e8c0217a0bdaa2eed54/google/resource_compute_instance_from_template.go#L40-L45
