### ISSUE TITLE
Testable State Migrations

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-plugin-sdk#243]
## Problem Statement

While testing state migrations is possible in a local unit test. There does not exist a formally supported method of testing a migration that requires interaction with APIs. As detailed in the comment below this is technically possible with some effort, it would be great if the acceptance test framework had a feature to make this development experience easier.

**Comment by bflad** [comment]
There's two scenarios that I believe its worth expanding on here:

* It is currently possible to test `MigrateState` and `StateUpgraders` in unit testing if they do not require API client calls. Example: https://github.com/terraform-providers/terraform-provider-aws/commit/42069b4585760440e99661bc08f718e254c19b4e
* It is only possible to test `StateUpgraders` that require API client calls by creating a separate acceptance test check function that fakes an old instance state and calls the state migration manually. Example: https://github.com/terraform-providers/terraform-provider-aws/pull/8776/files and https://github.com/terraform-providers/terraform-provider-aws/commit/3dc7d3c758cefac83dc8ece1ffd3212c75ce3fde

Essentially, it is not possible to test state migrations natively via the acceptance testing framework since the Terraform resources in the test configurations only work with the latest version of the resource schema.

**Comment by paultyng** [comment]
Going to merge this to #253
