### ISSUE TITLE
Attempting to implement Sweeper based on docs causes error when testing 

### ISSUE THREAD

**Issue by sanderblue** [hashicorp/terraform-plugin-sdk#244]
### Scenario
I attempted to add a [Sweeper](https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html) based on the docs to the New Relic Terraform Provider, however I could not get the implementation described in the docs to work when running `make testacc`.

Other questions came up as well. Why does the example in the docs involve the AWS domain specifically - i.e. `func sharedClientForRegion(region string)`? Region seems like it's specific to AWS.

In general is seems the error is coming from something in `github.com/hashicorp/terraform-plugin-sdk/helper/resource`. 

Even just added the following code causes an error when running `make testacc`:
```
package newrelic

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/helper/resource"
)

func TestMain(m *testing.M) {
	resource.TestMain(m)
}
```

### Terraform Version
Terraform v0.11.14

### Debug Output
Output of [make testacc](https://gist.github.com/sanderblue/e73a5cc06f61fa2a050ab6c51f0c4aa5)

### Expected Behavior
Acceptance tests should work and sweeper should sweep things clean.

### Actual Behavior
An error occurs
```
panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag": *tfdiags.rpcFriendlyDiag != *tfdiags.rpcFriendlyDiag
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Implement a Sweeper based on the [docs](https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html). 
2. Run `make testacc`
3. Receive interesting error 😎

**Comment by kmoe** [comment]
Thanks for the report, @sanderblue.

The error `registering duplicate types` occurs because `terraform-provider-newrelic` is importing both `github.com/hashicorp/terraform` and `github.com/hashicorp/terraform-plugin-sdk`, according to your [go.mod](https://github.com/terraform-providers/terraform-provider-newrelic/blob/d7a32a509e4a44d8186ea61f24bc266fab26079b/go.mod). These two Go modules contain packages providing many of the same types.

We recommend that providers upgrade to the standalone SDK Go module, `github.com/hashicorp/terraform-plugin-sdk`, which supersedes and is incompatible with `github.com/hashicorp/terraform`. It looks like the `terraform-plugin-sdk` dependency was added in https://github.com/terraform-providers/terraform-provider-newrelic/pull/189, but the `terraform` dependency was not removed.

Full instructions and an automated migration tool for migrating to the standalone plugin SDK can be found here:
https://www.terraform.io/docs/extend/plugin-sdk.html

Since you've already added `terraform-plugin-sdk` as a dependency, `tf-sdk-migrator migrate` won't automatically migrate your provider by default. You'll want to use `tf-sdk-migrator migrate -force`.

The Sweeper docs page uses the AWS example to demonstrate a paramaterised sweeper function i a realistic manner. Sweepers are domain-agnostic.

I'm closing this issue because it does not appear to be a bug in the SDK. Please reopen it if you believe you are seeing a bug after completing the SDK migration.
