### ISSUE TITLE
Removing a removed field from config shows a diff

### ISSUE THREAD

**Issue by danawillow** [hashicorp/terraform-plugin-sdk#285]
### SDK version

```
1.4.0
```

### Relevant provider source code

```go
			"zone": {
				Type:     schema.TypeString,
				Optional: true,
				Removed:  "Use location instead",
			},
```

### Terraform Configuration Files

```hcl
resource "google_container_cluster" "primary" {
  name               = "is-5265"
  zone               = "us-central1-a"
  initial_node_count = 1
}
```
updated to
```hcl
resource "google_container_cluster" "primary" {
  name               = "is-5265"
  location           = "us-central1-a"
  initial_node_count = 1
}
```

### Debug Output

Don't think it's relevant, but can grab if you'd like.

### Expected Behavior

shouldn't show a diff because when we change the field from `Deprecated` to `Removed`, the provider source code no longer has any way to handle a value in the removed field. We can work around this by setting the field to `Computed`, but I think it would be better if that happened automatically.

### Actual Behavior

diff shows in-place update:
```
      - zone                      = "us-central1-a" -> null
```

### Steps to Reproduce

Documented at https://github.com/terraform-providers/terraform-provider-google/issues/5265#issuecomment-569800664

### References

https://github.com/terraform-providers/terraform-provider-google/issues/5265

**Comment by radeksimko** [comment]
Apologies for the confusing UX here.

I assume that one of the reasons we present diff is because we still need to update the state to reflect the config change. While that may seem unimportant to the end user, it has to happen at some point.

We could probably (?) do that during refresh phase, but the SDK isn't in a position to dictate what happens in each phase, the core/protocol is.

The core however has no notion of `Removed` and so we'd need to bring that [into the protocol](https://github.com/hashicorp/terraform/blob/413e423bbabe2b3aea450572c29b54c39638c82a/docs/plugin-protocol/tfplugin5.1.proto#L81-L89) _and_ allow providers to somehow point to fields through the schema when deprecating them (not just in a plaint-text message), e.g. `RemovedInFavourOf`. Otherwise Terraform has no way of knowing these fields are related to each other.

This may be somewhat related to https://github.com/hashicorp/terraform-plugin-sdk/issues/19

**Comment by danawillow** [comment]
Thanks for taking a look, @radeksimko! Would it make sense on the SDK side to automatically treat all `Removed` fields as `Computed`, or is that ludicrous?

**Comment by radeksimko** [comment]
@danawillow Making a field `Computed` would indeed suppress the diff, but doesn't quite solve the problem I explained above - removing the deprecated/removed field from the state. It _probably_ doesn't harm to keep it there for some time, but I don't think it should be kept there forever.

Also if we want to implement the solution I proposed (delaying removal) in the future, then this short-term patch could turn into a costly technical debt as `Computed` is generally treated as "keep whatever is in state unchanged".

@hashicorp/terraform-core may have more context and may be able to provider some more ideas here, but this is my understanding based on my (possibly limited) knowledge of the codebase.

**Comment by jbardin** [comment]
I think the long term solution here should be fairly simple -- `ReadResource` should never return a value for a `Removed` field. This means it will already be removed from the state before we get to `PlanResourceChange`,  preventing a diff if it has also been removed from the config. If the config still has a value there, the SDK can return an error as it does already.

Offhand I can't think of any additional validation that we would be adding around `ReadResource` which would prevent this. The primary issue is that it's likely to interact in unexpected ways with the legacy SDK and shims.

**Comment by radeksimko** [comment]
Thanks, that does sound like a simple enough solution @jbardin 

I relabelled the issue just to reflect that the implementation doesn't require protocol change, but would be safer to implement in "protocol 5 only mode", which isn't a thing yet.

We can take a look at it once we finish the ongoing work of deprecating the old protocol (i.e. 0.11 and earlier versions).

**Comment by paultyng** [comment]
Going to merge this to #320 

I think we are going to drop `Removed` support in v2
