### ISSUE TITLE
Add helper for renaming a resource (and deprecating the old name)

### ISSUE THREAD

**Issue by paultyng** [hashicorp/terraform-plugin-sdk#306]
Similar to [`DataSourceResourceShim`](https://github.com/hashicorp/terraform-plugin-sdk/blob/0cc29fd5b60178cc6c6b85922b5fcd69e30409c3/helper/schema/data_source_resource_shim.go#L21), add ability to easily wrap a resource with a deprecation message suggesting its new name.

Implementation wise it would be nice to do something like the following in the **provider.go**:

```go
"new_resource_name": resourceFunc(),
"old_resource_name": ResourceRenameShim("new_resource_name", resourceFunc()),
```

**Comment by paultyng** [comment]
Sometime to investigate, do `state mv`'s still require the same resource type? If so, what would be the suggested upgrade path for folks that need to handle this?

**Comment by bflad** [comment]
Given that the `state mv` (and recent `moved` configuration block) requirement of matching resource types still applies today, I'm not sure we should introduce anything into this SDK around this concept until those design discussions have been fleshed out since right now this would leave practitioners in a bad spot of manually updating their state. My suggestion would be to subscribe to https://github.com/hashicorp/terraform/issues/27310 for further updates.
