### ISSUE TITLE
Provider produces invalid plan (but it works as expected)

### ISSUE THREAD

**Issue by LKaemmerling** [hashicorp/terraform-plugin-sdk#311]
### SDK version

```
1.6.0
```

### Relevant provider source code

https://github.com/terraform-providers/terraform-provider-hcloud/blob/master/hcloud/resource_hcloud_server.go#L90

### Terraform Configuration Files

```hcl
# Configure the Hetzner Cloud Provider
provider "hcloud" {
  token = "___token___"
}

# Create a server
resource "hcloud_server" "web" {
  name        = "node1"
  image       = "debian-9"
  server_type = "cx11"
}

```

### Debug Output

```
2020/02/03 22:52:12 [WARN] Provider "registry.terraform.io/-/hcloud" produced an invalid plan for hcloud_server.web, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .keep_disk: planned value cty.False does not match config value cty.NullVal(cty.Bool)
      - .backups: planned value cty.False does not match config value cty.NullVal(cty.Bool)
```
### Expected Behavior

There shouldn't be a warning. Booth fields are only a user provided value to enable/disable backups (as a sample). If the flag is not set, it should completely ignore the field (as it does at the moment)
### Actual Behavior

It throws this warning when setting TF_LOG to WARN.
### Steps to Reproduce

1. `terraform init`
2. `TF_LOG=WARN terraform apply`
### References

https://github.com/terraform-providers/terraform-provider-hcloud/issues/133

**Comment by bflad** [comment]
This error, that Terraform CLI downgrades to a warning log message as seen here for providers written with this SDK, is unfortunately expected behavior when a schema attribute does not include `Computed: true` with `Optional: true`. The reason being that the data handling internals of this SDK pre-date the concept of `null` within Terraform, so it cannot be appropriately handled and instead the SDK will default to the Go zero-value of the associated data type (e.g. TypeBool -> bool -> false). Trying to change this would be a large effort both for maintainers and provider developers who would need to update large amounts of data handling code. Terraform CLI should have some logic to silence some of these null to zero-value warnings for non-collection types when using this SDK, but its heuristics may not be perfect.

The good news is that over in [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework), an under-development next iteration of provider development, `null` is a native concept in data and it does not have this class of issue. 👍
