### ISSUE TITLE
Binary Test Driver: ExpectError fail to destroy for invalid config

### ISSUE THREAD

**Issue by appilon** [hashicorp/terraform-plugin-sdk#347]
### SDK version
```
2.0.0-dev, likely 1.7+
```

### Case
https://github.com/hashicorp/terraform-provider-http/blob/master/http/data_source_test.go#L216

### Expected Behavior
The test runs successfully, the expected error does not impede the system on cleanup

### Actual Behavior
While I believe the test has passed, the binary test driver errors out in cleanup `wd.RequireDestroy()`.
```
--- FAIL: TestDataSource_compileError (0.39s)
    testing_new.go:34: WARNING: destroy failed, so remote objects may still exist and be subject to billing
    testing_new.go:34: failed to destroy: terraform failed: exit status 1

        stderr:

        Error: Missing required argument

          on ../../../../../../../../var/folders/g3/9tzrnsmn7k7f7ynyqv4xc1v40000gn/T/tftest-terraform-provider-http234100929/work358369916/config213302542/terraform_plugin_test.tf line 2, in data "http" "http_test":
           2: data "http" "http_test" {

        The argument "url" is required, but no definition was found.
```
It's possible this test is anti-pattern to begin with and isn't widespread... we don't typically test required attributes through config and regexp 🤔, I think normally we put faith in our schema if something is marked required but is missing from config that terraform will error out.

**Comment by kmoe** [comment]
In this case, there is no state after the test step, so running `wd.RequireDestroy()` is unnecessary (and fails due to the invalid config). This is handled correctly in the legacy framework but was missed out of the new one. Raising PR to fix this.

Also, that error looks much nicer on my machine!

```
        Error: Missing required argument
        
          on config549720412/terraform_plugin_test.tf line 2, in data "http" "http_test":
           2: data "http" "http_test" {
        
        The argument "url" is required, but no definition was found.
```

I've added this detail to https://github.com/hashicorp/terraform-plugin-test/issues/15 - hopefully we can improve this aspect of the logging output.
