### ISSUE TITLE
Local build not going through: "make fmt" won't help to pass "fmtcheck" make: *** [GNUmakefile:34: fmtcheck] Error 1

### ISSUE THREAD

**Issue by caishaoping** [hashicorp/terraform-plugin-sdk#478]
### SDK version

```
module github.com/terraform-providers/terraform-provider-aws

go 1.13

require (
        github.com/aws/aws-sdk-go v1.32.3
        github.com/beevik/etree v1.1.0
        github.com/bflad/tfproviderdocs v0.6.0
        github.com/bflad/tfproviderlint v0.14.0
        github.com/client9/misspell v0.3.4
        github.com/golangci/golangci-lint v1.26.0
        github.com/hashicorp/aws-sdk-go-base v0.4.0
        github.com/hashicorp/go-cleanhttp v0.5.1
        github.com/hashicorp/go-multierror v1.1.0
        github.com/hashicorp/go-version v1.2.1
        github.com/hashicorp/terraform-plugin-sdk v1.14.0
        github.com/hashicorp/vault v0.10.4
        github.com/jen20/awspolicyequivalence v1.1.0
        github.com/katbyte/terrafmt v0.2.1-0.20200303174203-e6a3e82cb21b
        github.com/mitchellh/copystructure v1.0.0
        github.com/mitchellh/go-homedir v1.1.0
        github.com/pquerna/otp v1.2.0
        golang.org/x/tools v0.0.0-20200422022333-3d57cf2e726e
        gopkg.in/yaml.v2 v2.2.8
)


```

### Relevant provider source code

```go
...
```

### Terraform Configuration Files

```hcl
...
```

**Comment by caishaoping** [comment]
Here is additional info: 
1. SDK Version: 
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk",
  "Version": "v1.14.0"
}
2. Running Environment: 
cygwin64

**Comment by paddycarver** [comment]
It looks like you're trying to report an error with the AWS provider, not with the Terraform Plugin SDK. You can do that in [their issue tracker](https://github.com/terraform-providers/terraform-provider-aws/issues). If I've misunderstood and you're trying to report an error with the SDK, my apologies! We'll need some more information before we can do much, however, including the command you're running and the error output. I'm going to close this because, as I said, I think this is an issue with the AWS provider, not the SDK, but if it is an issue with the SDK, let us know in this issue and we can reopen it.

**Comment by caishaoping** [comment]
Hi There, 
Thank you for looking at this issue, sorry that I created the issue on Plugin SDK instead of AWS Provider. I will redirect the issue for the provider for the resolution. 
Thanks
