### ISSUE TITLE
Get Reserved fields value

### ISSUE THREAD

**Issue by FlorianJDF** [hashicorp/terraform-plugin-sdk#554]
Hello all,

# Terraform Version
```
$> terraform version
Terraform v0.11.14
```

# Issue
I am trying to get the value of the "alias" field of my provider.
But the GetOk if always returning False, nil.

```
provider "customprovider" {
  alias            = "test"
  should_state_dir = "./"
  log_path         = ".terraform/tmp/logs"
}
resource "custom_component" "mycomp" {
  provider = customprovider.test
  name = "cluster"
  ref = "2"
}
```
```
val, ok := data.GetOk(schema.ReservedProviderFields[0])

ok: false, val: %!s(<nil>).
```

I found nothing online for this case.
Is there a way to get the values of those reserved fields ?

Thank you

**Comment by paddycarver** [comment]
There is no way to retrieve this information from the SDK at the moment, that I know of at least. To the best of my knowledge, it's not even available to the SDK through the Terraform protocol.

**Comment by bflad** [comment]
Hi @FlorianJDF  👋  Thank you for raising this.

Resource meta-attributes, such as `depends_on`, `lifecycle`, `count`, etc. are reserved for Terraform CLI's sole usage and not designed to be part of the SDK nor sent across the protocol between CLI and providers. If it does happen to exist in the protocol in certain scenarios and the data is somehow available in the current SDK internals, it is likely an unintended implementation.

If there are certain details about resource operation ordering or other Terraform CLI implementation details that need to be relayed to providers for specific use cases, these would likely be implemented outside the existing configuration data constructs so the design can be tailored for the data and operational model we expect for provider implementations. Any design and implementation effort as part of the protocol and SDK is likely now to be focused in [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework), which is the next generation provider SDK as compared to this one.

Given all this, I'm going to close this issue out. If you have a very specific use case in mind, it might be best to file an issue in the [Terraform CLI repository](https://github.com/hashicorp/terraform/issues) first, since ultimately any design discussion and implementation work in this area would likely begin there in relation to what information should be available to providers. Thanks again.
