### ISSUE TITLE
acctest.RandTLSCert generated invalid private keys (key with <2048 bits)

### ISSUE THREAD

**Issue by LKaemmerling** [hashicorp/terraform-plugin-sdk#621]
### SDK version

```
v2.0.3
```

### Relevant provider source code

```go
rCert, rKey, err := acctest.RandTLSCert("myorg")
	rInt := acctest.RandInt()
	if err != nil {
		t.Fatal(err)
	}
```

### Terraform Configuration Files

```hcl
-
```

### Expected Behavior
The acctest generate private keys with 1024 bits (hardcoded -->https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/acctest/random.go#L145). The generated certificate is invalid for most distributions (as a sample Google Chrome requires TLS certificated with a private key >= 2048 since 2014.)

We use the function within our test for the Hetzner Cloud Load Balancer Feature and we noticed that the Load Balancer instance on the other end will never come up because of the invalid cert.

### Actual Behavior
Short Solution: Increase the bits to 2048
Long Term: Make the bits configurable (this might be a breaking change)

**Comment by LKaemmerling** [comment]
I noticed that within the AWS terraform provider you don't use the function, you use a custom function with 2048 bits already:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_iam_server_certificate_test.go#L195

**Comment by bflad** [comment]
Hi @LKaemmerling 👋 Thank you for raising this and apologies for the delayed response here.

At some point since this was raised, we began documenting the cryptographic specifics of the similar [`acctest.RandSSHKeyPair()`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest#RandSSHKeyPair) and recommending that testing with different or stronger security requirements should use code created outside this codebase. Similar documentation would apply for [`acctest.RandTLSCert()`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest#RandTLSCert). Security requirements are constantly evolving and it is untenable for this Go module to maintain all possible permutations required for cryptographic logic needed across the entire provider ecosystem without constant maintenance or inevitably needing to introduce breaking changes to the exported Go APIs. Future major versions of this code would likely remove helpers like these for that reason.

Apologies that this might not be the answer you are looking for here, but please reach out if you have questions. I'm going to leave this issue opened to ensure the documentation is appropriately added for `RandTLSCert()`.
