### ISSUE TITLE
Occasional ETXTBSY in plugintest

### ISSUE THREAD

**Issue by kmoe** [hashicorp/terraform-plugin-sdk#629]
Occasionally the binary test runner will fail with the following output:

```
cannot run Terraform provider tests: executable found at path /tmp/plugintest-terraform550986574/terraform is not terraform: fork/exec /tmp/plugintest-terraform550986574/terraform: text file busy
```

(from https://github.com/paultyng/terraform-provider-unifi/runs/1335952509?check_suite_focus=true)

Perhaps a race condition in writing to the same executable other tests are running. Needs investigation.

**Comment by paultyng** [comment]
still seeing this pretty frequently in my nightly tests on the Unifi provider using GitHub actions, unsure why.

**Comment by kmoe** [comment]
Could possibly be related to https://github.com/hashicorp/terraform-exec/issues/129

**Comment by bflad** [comment]
Since we haven't heard other reports of this, I'm going to go out on a limb and suggest we track this via https://github.com/hashicorp/terraform-exec/issues/129, and close this out.

One way to prevent any potential issues with overwriting Terraform CLI executables during acceptance testing (which I presume would be the cause of `ETXTBSY`-like errors) is ensuring that the binary installed prior to running the tests, either in the `PATH`, or explicitly setting it via `TF_ACC_TERRAFORM_PATH` environment variable. The [acceptance testing documentation](https://www.terraform.io/plugin/sdkv2/testing/acceptance-tests#requirements-and-recommendations) has been updated with this guidance, along with suggesting `hashicorp/setup-terraform` prior to running `go test` in GitHub Actions workflows.

Aside: [This LWN article on ETXTBUSY](https://lwn.net/Articles/866493/) published since this was raised is an interesting read.
