### ISSUE TITLE
Magic "terraform-" prefix is harmful in some cases.

### ISSUE THREAD

**Issue by crubier** [hashicorp/terraform-plugin-sdk#676]
### SDK version

```
all versions
```

### Use-cases

This line of the codebase defines a "magic" special prefix `terraform-` : 

https://github.com/hashicorp/terraform-plugin-sdk/blob/651b26a663d34daed50d135ddd25e170ff6c6aae/helper/resource/id.go#L10

Then some official providers use this magic prefix in heuristics to guess if a name was auto generated or not:

https://github.com/hashicorp/terraform-provider-aws/blob/e208508ede65805a23187128af515cb06bbcec39/aws/internal/naming/naming.go#L58

This causes issues down the line if the user happened to give a name that starts with this prefix `terraform-`:

https://github.com/hashicorp/terraform-provider-aws/issues/17017

And big bosse replied this :-) 

https://twitter.com/mitchellh/status/1347375993057464322

So I post this issue :-)

This magic prefix should be documented better, I saw no warning in the docs about NOT naming your resources with names or prefixes starting with `terraform-` anywhere. And `terraform-cluster-my-company` seemed like a perfectly good name for my company kubernetes cluster for example....

### Attempted Solutions

There are dirty workarounds for consequences of this problem down the line, but that's all I tried

### Proposal

- A solution could be to put a much more obfuscated magical prefix like `___terraform-` or something like that. But I guess it would not be retro-compatible...
- @mitchellh sugested to see if there can be some kind of detection/warning of that ( https://twitter.com/mitchellh/status/1347375993057464322 ) 
- At least, document this behaviour very clearly in the docs.

### References

- Bug caused by this : https://github.com/hashicorp/terraform-provider-aws/issues/17017
- Other bug caused by this:  https://github.com/hashicorp/terraform-provider-aws/issues/14898

**Comment by paultyng** [comment]
As you mention, this is a provider implementation bug and we can't really change the default prefix here without downstream state implications (also names starting with a prefix may not be compatible with some validation rules). 

This isn't an SDK issue, documentation or otherwise though, as we don't export any of the functions actually doing the checking. The detection/warning would need to be in any providers that have special functionality around this prefix. 

I'll chat with the AWS team though to see what they can do on their side.
