### ISSUE TITLE
Provide tfstate file (or a representation thereof) to TestCheckFuncs

### ISSUE THREAD

**Issue by gotascii** [hashicorp/terraform-plugin-sdk#68]
### Terraform Version

Terraform v0.7.0

I think this is a feature request, although I might just be missing something. Any help would be appreciated, thanks!

Currently, TestCheckFuncs are passed a *terraform.State which, as far as I understand, represents the state of the instances terraform is managing. That state is refreshed after create/update and before TestCheckFuncs are executed. This means that when testing various failure scenarios to ensure the proper implementation of partial state management, there is no way to inspect the state that would be written out to the tfstate file via the argument passed to the TestCheckFunc, as the two states can differ depending on the partial update implementation. How can I write a test that ensures my implementation of partial state management is as I expect? It would be nice if there was a way for TestCheckFuncs to inspect the state file, or some representation of the state that would be written to the file.

**Comment by bflad** [comment]
Hi folks 👋

Since this issue was introduced a long time ago, there has been a ton of changes between Terraform, terraform-plugin-sdk (especially v2 switching to calling normal Terraform CLI commands), and the [introduction of the terraform-plugin-testing module](https://discuss.hashicorp.com/t/announcing-the-terraform-plugin-testing-module/49914) ([migration guide](https://developer.hashicorp.com/terraform/plugin/testing/migrating)).

If this is still an issue or feature request, I believe it would be best submitted as a [new issue over in terraform-plugin-testing](https://github.com/hashicorp/terraform-plugin-testing/issues) as this Go module's `helper/resource package` is effectively being deprecated in preference of the same code over the new Go module. If this is still a question, I would suggest creating a topic in [HashiCorp Discuss](https://discuss.hashicorp.com/c/terraform-providers/tf-plugin-sdk/43) where there are more provider developers watching for topics than the repository maintainers in this GitHub issue tracker.

Thanks!
