### ISSUE TITLE
Default is ignored in properties with a DiffSuppressFunc

### ISSUE THREAD

**Issue by renier** [hashicorp/terraform-plugin-sdk#70]
### Terraform Version

Terraform v0.7.7
### Affected Resource(s)

Any resource with a property that has both a Default value and a DiffSuppressFunc
### Example code

https://github.com/softlayer/terraform-provider-softlayer/blob/aa6f146/softlayer/resource_softlayer_virtual_guest.go#L197-L209
### Description

If you have a property that has both a Default value and a DiffSuppressFunc, Terraform does not seem to use the Default value when generating the ResourceData for a new resource (no existing state yet).

Workaround: https://github.com/softlayer/terraform-provider-softlayer/blob/aa6f146/softlayer/resource_softlayer_virtual_guest.go#L310-L316
### Expected Behavior

For Terraform to use the Default value for optional properties when there is no existing resource state yet.

**Comment by bflad** [comment]
Hi folks 👋

A lot has changed with Terraform CLI and terraform-plugin-sdk between when this issue was raised and now. For example, there have been significant updates to the difference handling logic and the acceptance testing framework now uses real Terraform CLI commands and artifacts rather than re-implementing or emulating some of the previous Terraform core logic internally. State value checking should be wholly representative of an actual `terraform apply`.

If you are still running into problems in this area with recent versions of Terraform CLI and the SDK, my suggestion would be to open a new issue so we can take a fresh look. Thanks so much.
