### ISSUE TITLE
Better diff for large json or yaml properties 

### ISSUE THREAD

**Issue by tchiotludo** [hashicorp/terraform-plugin-sdk#744]
### SDK version

```
	github.com/hashicorp/terraform-plugin-sdk/v2 v2.5.0
```

### Use-cases
When you have a large / nested & dynamic properties, terraform can't handle this and suggest using a unique properties with json content. 
But since the user will feed the properties with a custom json string, there is no assomption the server will return the json (keys will be reordered depending on backend language). 
Same result for yaml (or backend interpreted language).

The first need is to avoid issuing diff and it's cover by `DiffSuppressFunc`
Here is how I handle it for yaml : https://github.com/kestra-io/terraform-provider-kestra/blob/97e8e435407f246410aa4cc0c7ab9e4f157cab69/internal/provider/provider.go#L122-L142

Now when I have true difference, terraform will look at the server value and compare with local values, the diff will be huge and disordered since we don't have any way to customize here the diff output 

### Proposal
Add a pre process method for every schema like `DiffSuppressFunc` that could be call `func PrepareValue(k, new string, d *schema.ResourceData) string` allowing to compute the string before analyse for diff from terraform. 

This allow to remove the need `DiffSuppressFunc` since we will reorder the json or yaml string before being compute by terraform

**Comment by bflad** [comment]
Hi @tchiotludo 👋  Thank you for raising this.

The intended difference handling for a particular schema attribute is via the `DiffSuppressFunc` -- this behavior in the SDK allows the provider to declare that the given plan and existing state values are semantically equivalent, even if they may contain syntactical differences (it can also be used in other scenarios, however that is how it can apply to the given use case). When it returns `true`, the SDK should return the existing state value back to Terraform rather than the planned value, meaning that Terraform should not show any difference for the attribute.

Very recently in v2.11.0, we have also introduced the [`Schema` type `DiffSuppressOnRefresh` field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Schema.DiffSuppressFunc). This allows the SDK to automatically check the `DiffSuppressFunc` during resource `Read` calls to `(*ResourceData).Set()`, preserving the old state value at this point in the resource lifecycle rather than updating the value with any semantically equivalent but syntactical differences. We anticipate that this new opt-in behavior (only in the interest of preserving backwards compatibility) is what most provider developers expected `DiffSuppressFunc` to do in the past already. It should be safe to try out across any attribute that implements `DiffSuppressFunc`, but of course we would recommend verifying expectations via acceptance testing where possible.

Barring these two mechanisms not working, a last resort option may be using the [Customizing Differences](https://www.terraform.io/plugin/sdkv2/resources/customizing-differences) functionality via the [`Resource` type `CustomizeDiff` field](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Resource.CustomizeDiff). For any attribute that is marked `Computed: true`, this allows the provider full control over what value that is sent back to Terraform during planning.

Hope this helps. If you have further questions about this class of provider development issue, I would encourage posting on the [HashiCorp Discuss forums](https://discuss.hashicorp.com/c/terraform-providers/31) where there are more provider developers watching rather than this particular issue tracker.
