### ISSUE TITLE
Setting Sensitive to true for a schema.TypeSet/TypeList parameter in a resource has no effect

### ISSUE THREAD

**Issue by ashishth09** [hashicorp/terraform-plugin-sdk#76]
### Terraform Version
0.9.5

### Affected Resource(s)
Writing a new resource where some of the fields are TypeSet and TypeList

`terraform plan`

For a TypeMap field I can see - 
    parameters.%:          "1"
    parameters.a:          "\<sensitive\>"
So this works.  

### Expected Behavior
All the fields in the Set or List should be marked as `sensitive`
For example - 
 tags.#:                   "1"
 tags.677375163:           "\<sensitive\>"

### Actual Behavior
TypeSet/TypeList fields for a resource appear as they are in the tf file

For example - 
 tags.#:                   "1"
 tags.677375163:           "sometag"

**Comment by paultyng** [comment]
Blocks (in Terraform core terms) cannot be marked Sensitive, the issue here is that the SDK does not correctly represent Terraform core's data model. Only attributes can be marked sensitive (and not nested fields on an object type attribute). This is unfortunately a limitation upstream and cannot be addressed just from the provider side. I'm going to merge this to #201 , but I think all the fixes will need to wait for a more holistic approach.
