### ISSUE TITLE
split empty string will get an array with a nil

### ISSUE THREAD

**Issue by ms-henglu** [hashicorp/terraform-plugin-sdk#769]
### SDK version

```
github.com/hashicorp/terraform-plugin-sdk v1.17.2
```

### Relevant provider source code

```go
if v, ok := config["default_documents"]; ok {
		input := v.([]interface{})

		log.printf("[INFO] %v", input)
	}
```

### Terraform Configuration Files

```hcl
default_documents = split(",", "")
```

### Debug Output

```
[<Nil>]
```

### Expected Behavior

It should be an empty array.
### Actual Behavior

It's an array contains a Nil
### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/11584

**Comment by bflad** [comment]
Hi @ms-henglu 👋  Thank you for raising this.

This edge case is a documented "feature" of the [Terraform configuration language `split()` function](https://www.terraform.io/language/functions/split). You can also verify this behavior when running `terraform console` locally:

```console
$ terraform console
> split(",", "")
tolist([
  "",
])
```

Any changes to the behavior of the `split()` function itself would need to occur in [Terraform CLI repository](https://github.com/hashicorp/terraform), which has the code for the function, so it would likely be best raised as an issue there if you wish to see this changed. Although to be upfront, I would imagine this falls under Terraform 1.0 compatibility promises so it is unlikely to get changed any time soon.

As for the behavior of this SDK converting the slice element from an empty string into a `nil` in this case, that unfortunately would fall under this project's compatibility promises and there are no more planned major releases of this project as its soon to be superseded by https://github.com/hashicorp/terraform-plugin-framework. Rather than keep this issue open in which no further work is expected, I'm going to close this out.

In the meantime, I'd suggest any provider code referencing `[]interface{}` data from `ResourceData` performs `nil` checks before accessing the expected underlying elements to protect from any panics.
