### ISSUE TITLE
Panic: Invalid diagnostic: empty summary

### ISSUE THREAD

**Issue by kavya498** [hashicorp/terraform-plugin-sdk#789]
### SDK version

```
v2.7.0
```
Hi,
We would want to understand, when we generally encounter empty summary crash
We have an existing infrastructure which uses terraform templates and was working perfectly fine earlier…
We had encounter this issue all of a sudden and it got resolved by itself…

It would be very helpful if we understand why we get this error… 
We don’t find any reference to resource / data source in the crash log…
How to debug and identify which has resulted in this error.. So that, our provider can be fixed accordingly…
### Debug Output
```
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00042f710, 0x2c9ba48, 0xc0000af680, 0xc0000af6c0, 0xc0000af680, 0x40ba05, 0x2636560)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:576 +0x4b9
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000b692a0, 0x2c9baf0, 0xc0000af680, 0xc000a374a0, 0xc000b692a0, 0xc000a519e0, 0xc0009c1ba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x26dd080, 0xc000b692a0, 0x2c9baf0, 0xc000a519e0, 0xc000a37440, 0x0, 0x2c9baf0, 0xc000a519e0, 0xc000b78d80, 0x20e)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000b96000, 0x2cb47b8, 0xc000403c80, 0xc0012c8b00, 0xc000674960, 0x39dd430, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000b96000, 0x2cb47b8, 0xc000403c80, 0xc0012c8b00, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00049a500, 0xc000b96000, 0x2cb47b8, 0xc000403c80, 0xc0012c8b00)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-ibm_v1.29.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behavior
Provider should not have crashed
### Actual Behavior
Crash with empty summary 

### Steps to Reproduce
It doesn't not happen everytime..

### References
https://github.com/IBM-Cloud/terraform-provider-ibm/issues/2918

**Comment by bflad** [comment]
Hi @kavya498 👋  Thank you for raising this and sorry you ran into trouble here.

There are a few pieces of context, which I feel are relevant here:

- This diagnostic panic on empty summary behavior during validation has been present since v2.0.0.
- The diagnostic validation code has no insight into where or how the diagnostic was generated.
- Most likely, this was generated from an `error` that was upgraded to a diagnostic. The empty summary may come from an `error` that is non-`nil`, but has an `Error()` return value that is `""`
- In this particular bug report, the `error` is coming from the resource `Exists` or `Read` function, which might help narrow down the root cause in your provider.

In my opinion though, a code panic is certainly less than ideal design choice here. It provides a stacktrace of where the problematic error/diagnostic came from, but forcibly exiting the provider in this manner could be potentially dangerous to in-flight provider operations.

There are a few considerations we can take to remediate the current behavior:

- Don't panic and treat the empty summary panic message as the new diagnostic summary. This has the benefit of being more friendly for providers running in production, however it does not provide context of how the situation occurred, so it makes it hard for providers to fix the issue.
- Ignore the diagnostic conversion of a non-`nil` error whose `Error()` method returns `""`. This could cause other issues in providers, where the halting behavior of the error was expected.
- Inject more logging statements into the SDK, noting when error/diagnostics are returned from provider and SDK defined logic.
- Adding unexported field(s) to diagnostics which can denote where it was generated, or save an original `error`, then including that output in diagnostic details, if that field is empty.

I'm leaning towards a combination of not panicking and injecting more SDK logging. The last option is probably the most ideal, however it would likely require some more design thinking.
