### ISSUE TITLE
Terraform Crash

### ISSUE THREAD

**Issue by rapullur** [hashicorp/terraform-plugin-sdk#89]
Hi everyone , Please need advice/help. I am getting below error message " !!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Terraform crashed! This is always indicative of a bug within Terraform.
" in pre-prod env, however its working fine in other env like ( Prod) . Current installed version Terraform v0.9.11 .

**Comment by radeksimko** [comment]
Hi @rapullur 
sorry for the delay in responding to this report, but it looks like the bug was fixed. At least I was not able to reproduce it in `0.10`, `0.11` nor `0.12`.

The config provided in https://github.com/hashicorp/terraform/issues/16795#issue-277986422 doesn't seem to be valid for any of these versions. The AWS provider 1.3.1 (which seems to have been in use) never nested fields like `alarm_actions`, `alarm_description` or `actions_enabled` under `dimensions`. `dimensions` was always `TypeMap` which is why Terraform would not complain about "invalid" fields, as it's practically freeform. Older versions of Terraform will however complain about invalid types under TypeMap.

Regardless 0.12 introduced much stronger config validation which runs very early on and so it's highly unlikely (if not impossible) for the provider/SDK to receive such invalid config which would cause such crash.

Here is a config very close to yours which I used when trying to reproduce it:

```hcl
data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "web" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  tags = {
    Name = "HelloWorld"
  }
}

resource "aws_cloudwatch_metric_alarm" "statusCheckFailed" {
  alarm_name = "statusCheckFailed"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods = 1
  metric_name = "StatusCheckFailed_System"
  namespace = "AWS/EC2"
  period = 120
  statistic = "Maximum"
  threshold = 1
  insufficient_data_actions = []
  dimensions = {
    Something = 2
    InstanceId = "${aws_instance.web.id}"
  }
  alarm_actions = [
    "arn:aws:sns:us-east-1:848676982977:ckc-preprod-lambda-ec2stopstart",
    "arn:aws:automate:us-east-1:ec2:recover",
  ]
  alarm_description = "StatusCheckFailed"
  actions_enabled = true
}
```

With that I'm going to close this issue, but feel free to raise a separate one with a fresh crash log and config if you encounter this in 0.12.
