### ISSUE TITLE
Crash when using `aws_route53_zone`

### ISSUE THREAD

**Issue by shakefu** [hashicorp/terraform-plugin-sdk#94]
### Terraform Version

```
$ terraform --version
Terraform v0.11.2
+ provider.aws v1.7.0
+ provider.ignition v1.0.0
+ provider.random v1.1.0

```

### Terraform Configuration Files

```hcl
# dns.tf
data "aws_route53_zone" "domain" {
  name = "domain.io"
}

resource "aws_route53_zone" "vpc" {
  name = "vpc.${data.aws_route53_zone.domain.name}"
  tags = ["${var.tags}"]
}

resource "aws_route53_record" "vpc_ns" {
  zone_id = "${aws_route53_zone.vpc.zone_id}"
  name    = "vpc.${data.aws_route53_zone.domain.name}"
  type    = "NS"
  ttl     = "5"

  // records = ["${aws_route53_zone.vpc.name_servers}"]
  records = [
    "${aws_route53_zone.vpc.name_servers.0}",
    "${aws_route53_zone.vpc.name_servers.1}",
    "${aws_route53_zone.vpc.name_servers.2}",
    "${aws_route53_zone.vpc.name_servers.3}",
  ]
}

# tags.tf
variable "tags" {
  default = {
    environment = "dev"
    phase       = "research"
    provisioner = "terraform"
    unit        = "multi"
  }

  type = "map"
}
```

### Crash Output

https://gist.github.com/shakefu/48cbd993c8b38c023fb8e67efa69fff3

### Expected Behavior

A new plan should be generated including a subdomain zone.

### Actual Behavior

Terraform crashes.

### Steps to Reproduce

(Probably)
1. Create DNS zone with `tags` key.
2. Crash!

### Additional Context

Found this as part of a large configuration. Was able to replicate with the minimal HCL (private domains redacted) above.

**Comment by radeksimko** [comment]
Hi @shakefu
Firstly I want to thank you for providing the config - this was incredibly helpful.

It is clear to me that the crash comes from this line:
https://github.com/hashicorp/terraform/blob/e0fd3ddd704b230897723a7ca251f36b71c2b67a/helper/schema/field_reader_config.go#L170
which still exists today in the current SDK in the same form and shape:
https://github.com/hashicorp/terraform-plugin-sdk/blob/b43818996f728dfeaf444519052cdb44d28a7abc/helper/schema/field_reader_config.go#L187

I was able to reproduce it under `0.11.14`. It can be triggered by setting any map field (such as `tags` in your config) to a list.

Terraform 0.12 (with HCL2) validates configuration very early on, before the provider (SDK) lines are even executed. The SDK will therefore always receive valid HCL2 configuration from 0.12 which should not cause such crash.

Here is output from `terraform apply` (w/ Terraform 0.12.0) which doesn't crash anymore and instead returns human-readable error:

```
$ terraform apply

Error: Incorrect attribute value type

  on main.tf line 12, in resource "aws_route53_zone" "vpc":
  12:   tags = ["${var.tags}"]

Inappropriate value for attribute "tags": map of string required.
```

I will therefore conclude that this bug is fixed in 0.12 and users can upgrade to any 0.12 version.
