### ISSUE TITLE
d.Set doesn't work on not computed values

### ISSUE THREAD

**Issue by luispresuelVenafi** [hashicorp/terraform-plugin-sdk#951]
### SDK version
```
latest 2.14
```
As part migration from SDKv1 to SDKv2 we noticed of our [provider ](https://github.com/hashicorp/terraform-plugin-sdk)that the d.Set doesn't work anymore for attributes of a resource that are not computed. When trying to "correct" the value from our provider of the `expiration_window` attribute during this section of the code our resource: https://github.com/Venafi/terraform-provider-venafi/blob/master/venafi/resource_venafi_certificate.go#L528
it will no longer take effect (we want this behavior because we do a validation after our certificate resource having created that may return a new value for the expiration_window that we want to correct). Is that now intended behavior for the SDKv2? If so, what could be the better approach to reach our desired behavior for our use case.  Not sure if is this a bug and there's plan to fix it in the future.

### Expected Behavior
d.Set should also update the value from the resource attribute even if the resource is not computed.

### Actual Behavior
d.Set doesn't update the value if the resource is not computed.

**Comment by bflad** [comment]
Hi @luispresuelVenafi 👋  Thanks for raising this and sorry you ran into trouble here.

Looking real quickly at that resource, it looks like its taking advantage of the [`Exists` functionality](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Resource.Exists) that was [deprecated with v2](https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide#deprecation-of-helper-schema-existsfunc):

https://github.com/Venafi/terraform-provider-venafi/blob/a157e1ddb60bf4f730b47b02db399ecb1c25d821/venafi/resource_venafi_certificate.go#L226-L230

Does it work if you move that logic into the `Read` function (substituting any `return false, nil` with `d.SetId("")` and `return nil` to signal to Terraform CLI that the resource no longer exists)?

I'm not sure if it was intentional that `Exists` in v1 supported modifying the `ResourceData`, but the logic around the functionality in v2 certainly does not now:

https://github.com/hashicorp/terraform-plugin-sdk/blob/bb44c873a83f37a33a0fc3ae0b9385294583c337/helper/schema/resource.go#L978-L1002

If you haven't seen already, the [v2 Upgrade Guide](https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide) might have some other helpful tidbits. 👍

**Comment by bflad** [comment]
I would certainly expect any calls to `d.Set()` with error checking to return some form of error if the value was somehow incorrect for the situation, such as an incorrect type. So that doesn't seem to be the case.

If you've already tried using `Read` instead of `Exists` (which, at least in v2, is only providing a copy of `ResourceData` to provider logic so any `d.Set()` calls would not effect the state), then my next recommendation would be to try running Terraform CLI with logging enabled, e.g. `TF_LOG=TRACE terraform apply`.

---

I see you amended your above comment to mention this is only during acceptance testing. Can you show your testing code and the test failure output?

**Comment by luispresuelVenafi** [comment]
Sure

in the new resource_test file we'd have the following:

These imports:
```
package venafi

import (
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
	"os"
	"regexp"
	"strconv"
	"testing"
)
```
Then the following strings fro the provider and resource
```
var (
	environmentVariables = fmt.Sprintf(`
variable "TPP_USER" {default = "%s"}
variable "TPP_PASSWORD" {default = "%s"}
variable "TPP_URL" {default = "%s"}
variable "TPP_ZONE" {default = "%s"}
variable "TPP_ZONE_ECDSA" {default = "%s"}
variable "TRUST_BUNDLE" {default = "%s"}
variable "CLOUD_URL" {default = "%s"}
variable "CLOUD_APIKEY" {default = "%s"}
variable "CLOUD_ZONE" {default = "%s"}
variable "TPP_ACCESS_TOKEN" {default = "%s"}
`,
...
vaasProvider = environmentVariables + `
provider "venafi" {
	alias = "vaas"
	url = "${var.CLOUD_URL}"
	api_key = "${var.CLOUD_APIKEY}"
	zone = "${var.CLOUD_ZONE}"
}
`
...
vaasConfig = `
%s
resource "venafi_certificate" "vaas_certificate" {
	provider = "venafi.vaas"
	common_name = "%s"
	%s
	key_password = "%s"
	expiration_window = %d
}
output "certificate" {
	value = "${venafi_certificate.vaas_certificate.certificate}"
}
output "private_key" {
	value = "${venafi_certificate.vaas_certificate.private_key_pem}"
	sensitive = true
}
output "expiration_window" {
	value = "${venafi_certificate.vaas_certificate.expiration_window}"
}`
...
```
Then the following test:
```
func TestVaasSignedCertUpdateWithCertDurationFromZoneWithGreaterExpWindow(t *testing.T) {
	/*
		We test to create a certificate on first step that has duration less from zone (without setting valid_days)
		than the expiration_window: It should create a Terraform state with an expiration_window as same as the cert duration.
		We expect a not empty plan due to the expiration_window being equal to cert duration
	*/
	data := testData{}
	rand := randSeq(9)
	domain := "venafi.example.com"
	data.cn = rand + "." + domain
	data.private_key_password = "123xxx"
	data.key_algo = rsa2048
	data.expiration_window = 170
	currentExpirationWindow := data.expiration_window
	config := fmt.Sprintf(vaasConfig, vaasProvider, data.cn, data.key_algo, data.private_key_password, data.expiration_window)
	t.Logf("Testing Cloud certificate with config:\n %s", config)
	resource.Test(t, resource.TestCase{
		ProviderFactories: testAccProviderFactories,
		Steps: []resource.TestStep{
			resource.TestStep{
				Config: config,
				Check: func(s *terraform.State) error {

					err := checkStandardCert(t, &data, s)
					if err != nil {
						return err
					}
					err = checkCertExpirationWindow(t, &data, s)
					if err != nil {
						return err
					}
					if currentExpirationWindow == data.expiration_window {
						return fmt.Errorf(fmt.Sprintf("expiration window should have changed during enroll. current: %s got from zone: %s", strconv.Itoa(currentExpirationWindow), strconv.Itoa(data.expiration_window)))
					}
					return nil

				},
				ExpectNonEmptyPlan: true,
			},
			resource.TestStep{
				Config:             config,
				ExpectNonEmptyPlan: true,
				Check: func(s *terraform.State) error {
					t.Log("Testing TPP certificate update")
					gotSerial := data.serial
					err := checkStandardCert(t, &data, s)
					if err != nil {
						return err
					} else {
						t.Logf("Compare updated original certificate serial %s with updated %s", gotSerial, data.serial)
						if gotSerial == data.serial {
							return fmt.Errorf("serial number from updated certificate %s is the same as "+
								"in original number %s", data.serial, gotSerial)
						} else {
							return nil
						}
					}
				},
			},
		},
	})
}
```

And then the check function for the expiration were we gather the value from the outputs:
```
func checkCertExpirationWindow(t *testing.T, data *testData, s *terraform.State) error {
	t.Log("Getting expiration_window from terraform state", data.cn)
	expirationWindowUntyped := s.RootModule().Outputs["expiration_window"].Value
	expirationWindowString, ok := expirationWindowUntyped.(string)
	if !ok {
		return fmt.Errorf("output for \"expiration_window\" was not defined")
	}
	expirationWindow, err := strconv.Atoi(expirationWindowString)
	if err != nil {
		return fmt.Errorf("output for \"expiration_window\" is not a valid integer")
	}
	data.expiration_window = expirationWindow
	return nil
}
```
One thing to notice here is that before we have to cast as integer as in here: https://github.com/Venafi/terraform-provider-venafi/blob/master/venafi/resource_venafi_certificate_test.go#L1245 and now we expect an string from the `s.RootModule().Outputs["expiration_window"].Value`

This is error I get if I run the test:
```
   test_util.go:191: Getting expiration_window from terraform state a5jmkhjsf.venafi.example.com
    resource_venafi_certificate_test.go:524: Step 1/2 error: Check failed: expiration window should have changed during enroll. current: 170 got from zone: 170
--- FAIL: TestVaasSignedCertUpdateWithCertDurationFromZoneWithGreaterExpWindow (13.74s)
```

Which makes sence, since the d.Set didn't effect during the test or could related to the `s.RootModule` ?

**Comment by bflad** [comment]
Ah ha -- this information is super helpful. One of the big changes from v1 to v2 was that the acceptance testing framework was changed from using (or rather, duplicating) Terraform code to handle its internals to actually calling Terraform CLI commands. It's entirely possible that certain internals of `terraform.State` passed to provider-defined `TestCheckFunc` could've changed in the process.

If you haven't seen, the SDK does provide some helpers that could simplify this testing code (and potentially fix it in this case), e.g. [`resource.TestCheckResourceAttr`](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource#TestCheckResourceAttr). In general, you can also avoid having `output`s in the testing configuration and check the resource state directly.

I'm wondering if swapping out the custom `TestCheckFunc` for some of the standard `helper/resource` checks might help alleviate any testing framework oddities rather than trying to access some of its internal data directly.
