### ISSUE TITLE
Terraform version for the User-Agent string is hard coded to v0.10.6

### ISSUE THREAD

**Issue by WodansSon** [hashicorp/terraform-plugin-sdk#97]
### Terraform Version
```
Terraform v0.11.2
```

### Terraform Configuration Files
```hcl
N/A
```

### Debug Output
N/A

### Crash Output
N/A

### Expected Behavior
The actual version of the Terraform Runtime should be emitted.

### Actual Behavior
Terraform version is [hard coded](https://github.com/terraform-providers/terraform-provider-azurerm/blob/51d26fd486a2e5f652ead84a5bf82947b23aabcb/vendor/github.com/hashicorp/terraform/terraform/version.go#L26:6) to version 10.6

### Steps to Reproduce
1. Use latest Terraform(v0.11.2) to provision azure resource, please specify the provider version to be latest.
2. Search from ARM log, you will see the userAgent string is always v0.10.6

**Comment by radeksimko** [comment]
Hi @WodansSon 
as I explained in https://github.com/hashicorp/terraform/pull/22272 this is merely a side effect of how providers got Terraform version previously and many still do today due to this version not being available via the gRPC protocol until Terraform 0.12.

The version became available in the protocol in 0.12 and we introduced [a helper `httpclient.TerraformUserAgent(version)`](https://github.com/hashicorp/terraform/pull/22272) leveraging this version for the most common use case - sending `User-Agent` header to upstream APIs.

Additionally any provider migrating to the standalone SDK (where this issue has been already migrated to) is practically forced to report correct version from the protocol as certain functions and packages exposing the "old way" of getting (usually incorrect) version were removed. Read more about [deprecations](https://www.terraform.io/docs/extend/plugin-sdk.html#deprecations) in our dedicated docs page.

Here is an example PR which is leveraging this new helper function and dynamic Terraform version sent via the gRPC protocol: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/620/files

We plan to make some further improvements around User-Agent specific logic - discuss whether and how we can standardize this between providers, but that is outside of the context of this issue.

With that I'm going to close this.
